# GitHub Actions Part1 - Basics
#Copyleft by Evgen Korban 2022

name: My-GitHub-Actions-Basics
env:
  APPLICATION_NAME: "MuFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:  
  push:
    branches: 
      - main 
      
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
    
    -name: Execute few commands
      run:
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Apllication name: ${{ env.APPLICATION_NAME }}"
     
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
   
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
    
    
