# GitHub Actions Part2 - Basics
# Copyleft (c) by Evgen Korban 2022

name: My-GitHub-Actions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"


on:  
  push:
    branches: 
      - main 
      
      
jobs:
  my_testing:
    runs-on: ubuntu-latestt
    
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing job"
    
    - name: Execute few commands
      run:
        echo "Apllication name is ${{ env.APPLICATION_NAME }}"
        echo "Hello Message1"
        echo "Hello Message2"
        
        
    - name: Git clone my repo
      uses: actions/checkout@v1  #закидываем все наши файлы в ОС Докер-контейнера, с помощью внешних скриптов.
    
    - name: List current folder
      run: ls -la   #выводим список уже новых файлов на Докер-контейнере

    - name: Lets test some packages, if the are here1
      run: aws --version
     

    - name: Lets test some packages, if the are here2
      run: zip --version
        

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job Level Variable1"
      VAR2: "This is Job Level Variable2"
      
   
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello World from Deploy job"
    
    - name: Print env vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
        
      env:
        LOCAL_VAR: "This is Super local Environment variable"
      
    
    - name: Printing Deployment Package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
      
      
      
      
      
